import json
import os
import sys

TRANSLATIONS = {
    "en": {
        "title": "ChatCellAnno",
        "step1": "Step 1: Data Source",
        "placeholder_path": "Drag & drop file here or browse...",
        "browse": "Browse",
        "scanpy": "Scanpy (Python)",
        "seurat": "Seurat (R)",
        "step2": "Step 2: Enrichment Analysis",
        "species": "Species:",
        "tissue": "Tissue:",
        "top_n": "Top Markers:",
        "exclude": "Exclude Types (optional):",
        "prompt_mode": "Prompt Mode:",
        "concise": "Concise",
        "detailed": "Detailed",
        "step3": "Step 3: Prompt Configuration",
        "gen_btn": "Generate & Copy Prompt",
        "gen_btn_enrich": "Run Enrichment Analysis",
        "step4": "Step 4: AI Response",
        "placeholder_resp": "Paste AI response here...",
        "process_btn": "Process AI Output",
        "step5": "Step 5: Spare",
        "code_label": "Generated Code:",
        "copy_code": "Copy Code",
        "gen_report": "Generate Analysis Report",
        "report_success": "Analysis report saved!",
        "report_template": "# ChatCellAnno Analysis Report\n\n## 1. Project Info\n- **Date**: {date}\n\n## 2. Cell Type Annotations\n{results}\n\n## 3. Enrichment Analysis\n{enrichment}\n\n---\n*Generated by ChatCellAnno*",
        "default_page": "Default Page:",
        "browser_label": "Browser:",
        "go": "Go",
        "refresh": "Refresh",
        "enrich_running": "Enrichment Analysis in Progress...",
        "clean": "Clean",
        "enrich_complete": "Analysis Complete!",
        "local": "Local Database",
        "online": "Online (Enrichr)",
        "enrich_source": "Enrichment Source:",
        "guide": "User Guide",
        "settings": "Settings",
        "add_web": "+ Web",
        "language": "Language",
        "confirm_delete": "Confirm Delete",
        "delete_msg": "Are you sure you want to delete '{}'?",
        "last_service_msg": "Cannot delete the last service.",
        "success": "Success",
        "prompt_copied": "Prompt copied! Paste it into the browser on the right.",
        "error": "Error",
        "file_not_found": "File not found!",
        "warning": "Warning",
        "paste_warning": "Please paste the AI response first.",
        "no_file_title": "No Marker File",
        "no_file_msg": "No marker file selected.\n\nDo you want to generate code using ONLY the AI response? (Ensure the AI output contains Cluster IDs)",
        "edit_web": "Edit Web Link",
        "add_web_title": "Add Web Link",
        "web_name": "Web Name:",
        "web_url": "URL:",
        "save": "Save",
        "add": "Add",
        "cancel": "Cancel",
        "input_error": "Input Error",
        "input_error_msg": "Please provide a valid name and URL (starting with http/https).",
        "restart_msg": "Please restart the application to apply language changes.",
        "edit_fmt": "Edit '{}'",
        "delete_fmt": "Delete '{}'",
        "cannot_delete_last": "Cannot delete the last service.",
        "delete_confirmation": "Are you sure you want to delete '{}'?",
        "edit_web_link": "Edit Web Link",
        "add_web_link": "Add Web Link",
        "url": "URL:",
        "restart_required": "Restart Required",
        "language_changed": "Language changed to {}. Please restart the application.",
        "web_plus": "+ Web",
        "toggle_language": "Toggle Language",
        "open_in_new": "Open in New Window",
        "initial_page": "Default Page",
        "chat_services": "Chat Services",
        "bookmarks": "Bookmarks",
        "lang_zh": "Chinese",
        "lang_en": "English",
        "tab_browser": "AI Browser",
        "tab_enrichment": "Enrichment Results",
        "tab_genome": "Genome Comparison",
        "search": "Search",
        "placeholder_gene": "Enter gene name (e.g. Prrx1)",
        "no_results": "No matching records found in genome folder.",
        "local_db_hint": "Please click the folder button to select database directory",
        "optional_matrix": "Key Genes Expression Matrix (Optional):",
        "matrix_hint": "CSV with clusters as rows and genes as columns...",
        "visual_context": "Visual Summary (UMAP/t-SNE) (Optional)",
        "paste_img": "Paste Image from Clipboard",
        "clear_img": "Clear",
        "img_type": "Image Type:",
        "no_img_loaded": "No image loaded",
        "copy_img_ai": "Copy Image to AI Chat",
        "copy_img_success": "Image copied! Paste it into your AI Chat now.",
        "no_img_clipboard": "No image data found in clipboard! Make sure you copied an actual image (not a file).",
        "api_settings": "API Settings",
        "use_api": "Auto-Call via API",
        "api_key": "API Key:",
        "api_base": "Base URL:",
        "api_model": "Model Name:",
        "api_calling": "Calling API, please wait...",
        "api_success": "API response received successfully!",
        "query_mode": "Query Mode:",
        "browser_query": "Via Browser",
        "api_query": "Via API",
        "gen_prompt_file": "Generate Prompt File",
        "drag_info": "Hold & Drag files to Browser Chat",
        "query_btn": "Query",
        "marker_list_label": "Differential Gene List (Required):",
        "enrich_assist_label": "Perform enrichment to assist AI annotation (Optional)",
        "panels_control": "Show Panels"
    },
    "zh": {
        "title": "ChatCellAnno - 单细胞注释助手",
        "step1": "步骤 1: 数据源",
        "placeholder_path": "拖放文件或点击浏览...",
        "browse": "浏览",
        "scanpy": "Scanpy (Python)",
        "seurat": "Seurat (R)",
        "step2": "步骤 2: 提示词配置",
        "species": "物种:",
        "tissue": "组织:",
        "top_n": "Top Markers:",
        "exclude": "排除类型 (可选):",
        "prompt_mode": "提示词模式:",
        "concise": "简洁",
        "detailed": "详细",
        "step3": "步骤 3: AI 回答结果",
        "gen_btn": "生成并复制提示词",
        "gen_btn_enrich": "运行富集分析",
        "step4": "步骤 4: 导出代码",
        "placeholder_resp": "在此粘贴 AI 回复...",
        "process_btn": "处理 AI 输出",
        "step5": "步骤 5: 备用",
        "code_label": "生成的代码:",
        "copy_code": "复制代码",
        "gen_report": "生成分析报告",
        "report_success": "分析报告已保存！",
        "report_template": "# ChatCellAnno 单细胞注释分析中心报告\n\n## 1. 项目基本信息\n- **日期**: {date}\n\n## 2. 细胞类型注释结果\n{results}\n\n## 3. 功能富集分析汇总\n{enrichment}\n\n---\n*本报告由 ChatCellAnno 自动化注释系统生成*",
        "default_page": "默认主页:",
        "browser_label": "浏览器:",
        "go": "前往",
        "refresh": "刷新",
        "enrich_running": "正在进行富集分析...",
        "clean": "清空",
        "enrich_complete": "分析完成！",
        "local": "本地数据库",
        "online": "在线 (Enrichr)",
        "enrich_source": "富集数据源:",
        "guide": "用户指南",
        "settings": "设置",
        "add_web": "+ Web",
        "language": "语言 / Language",
        "confirm_delete": "确认删除",
        "delete_msg": "确定要删除 '{}' 吗?",
        "last_service_msg": "无法删除最后一个服务。",
        "success": "成功",
        "prompt_copied": "提示词已复制！请粘贴到右侧浏览器中。",
        "error": "错误",
        "file_not_found": "未找到文件！",
        "warning": "警告",
        "paste_warning": "请先粘贴 AI 回复内容。",
        "no_file_title": "未选择 Marker 文件",
        "no_file_msg": "未检测到 Marker 文件。\n\n是否仅根据 AI 回复生成代码？(请确保 AI 回复中包含 Cluster ID)",
        "edit_web": "编辑网页链接",
        "add_web_title": "添加网页链接",
        "web_name": "名称:",
        "web_url": "链接 (URL):",
        "save": "保存",
        "add": "添加",
        "cancel": "取消",
        "input_error": "输入错误",
        "input_error_msg": "请输入有效的名称和网址 (需以 http/https 开头)。",
        "restart_msg": "语言设置已更改，请重启软件生效。",
        "edit_fmt": "编辑 '{}'",
        "delete_fmt": "删除 '{}'",
        "cannot_delete_last": "无法删除最后一个服务。",
        "delete_confirmation": "您确定要删除 '{}' 吗？",
        "edit_web_link": "编辑链接",
        "add_web_link": "添加链接",
        "url": "URL：",
        "restart_required": "需要重启",
        "language_changed": "语言已切换为 {}。请重启应用以生效。",
        "web_plus": "+ 网站",
        "toggle_language": "切换语言",
        "open_in_new": "在新窗口打开",
        "initial_page": "默认主页",
        "chat_services": "聊天服务",
        "bookmarks": "书签",
        "lang_zh": "中文",
        "lang_en": "English",
        "tab_browser": "AI 浏览器",
        "tab_enrichment": "功能富集结果",
        "tab_genome": "基因序列比对",
        "search": "搜索",
        "placeholder_gene": "输入基因名 (如 Prrx1)",
        "no_results": "未在 genome 文件夹下找到匹配项。",
        "local_db_hint": "请点击右侧文件夹按钮选择本地数据库目录",
        "optional_matrix": "关键基因表达矩阵 (可选):",
        "matrix_hint": "聚类为行，基因为列的 CSV 文件...",
        "visual_context": "UMAP/t-SNE等聚类图截图 (可选)",
        "paste_img": "从剪贴板粘贴图像",
        "clear_img": "清除",
        "img_type": "图像类型 :",
        "no_img_loaded": "未加载图像",
        "copy_img_ai": "带图像复制",
        "copy_img_success": "图像已复制！现在您可以将它粘贴到 AI 的对话框中了。",
        "marker_list_label": "差异基因列表 (必选):",
        "enrich_assist_label": "进行功能富集以辅助 AI 注释 (可选)",
        "panels_control": "显示面板 (Panels)",
        "no_img_clipboard": "剪贴板中没有图像数据！\n如果是复制的图片文件而不是它里面的图像内容，请在画图、微信或系统自带图片查看器中打开后，按 Ctrl+C 复制。",
        "api_settings": "API 设置",
        "use_api": "直接通过 API 自动查询",
        "api_key": "API 密钥 (Key):",
        "api_base": "接口地址 (Base URL):",
        "api_model": "模型名称 (Model):",
        "api_calling": "正在调用 API, 请稍候...",
        "api_success": "API 响应已成功接收！",
        "query_mode": "查询模式:",
        "browser_query": "通过浏览器查询",
        "api_query": "通过 API 查询",
        "gen_prompt_file": "生成提示词文件",
        "drag_info": "在此处按住并拖拽到浏览器",
        "query_btn": "查询"
    }
}

class ConfigManager:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(ConfigManager, cls).__new__(cls)
            cls._instance.initialize()
        return cls._instance

    def initialize(self):
        # Determine base directory: Use EXE parent directory even when frozen
        if getattr(sys, 'frozen', False):
            # If running as compiled EXE, use the folder where .exe exists
            base_dir = os.path.dirname(sys.executable)
        else:
            # If running as script, use script directory
            base_dir = os.path.dirname(os.path.abspath(__file__))
            if "chatcellanno" in base_dir:
                base_dir = os.path.dirname(base_dir) # Go up to project root

        self.config_paths = {
            "config": os.path.join(base_dir, "config.json"),
            "web_storage": os.path.join(base_dir, "chatcellanno_web_data")
        }
        
        self.language = "en"
        self.chat_services = {
            "DeepSeek": "https://chat.deepseek.com",
            "ChatGPT": "https://chatgpt.com", 
            "Claude": "https://claude.ai",
        }
        self.default_service = "DeepSeek"
        self.session_params = {
            "species": "Human",
            "tissue": "PBMC",
            "top_n": "10",
            "exclude": "",
            "prompt_mode": "concise"
        }
        self.api_settings = {
            "api_key": "",
            "api_base": "https://api.siliconflow.cn/v1",
            "api_model": "Qwen/Qwen2.5-72B-Instruct"
        }
        self.last_db_path = ""
        
        self.load_config()

    def load_config(self):
        if os.path.exists(self.config_paths["config"]):
            try:
                with open(self.config_paths["config"], "r", encoding="utf-8") as f:
                    config = json.load(f)
                    self.default_service = config.get("default_service", "DeepSeek")
                    loaded_params = config.get("session_params", {})
                    self.session_params.update(loaded_params)
                    loaded_api = config.get("api_settings", {})
                    self.api_settings.update(loaded_api)
                    self.last_db_path = config.get("last_db_path", "")
                    custom_services = config.get("chat_services")
                    self.language = config.get("language", "en") 
                    if custom_services:
                        self.chat_services = custom_services
            except:
                pass

    def save_config(self):
        config = {
            "default_service": self.default_service,
            "session_params": self.session_params,
            "api_settings": self.api_settings,
            "chat_services": self.chat_services,
            "language": self.language,
            "last_db_path": self.last_db_path
        }
        try:
            with open(self.config_paths["config"], "w", encoding="utf-8") as f:
                json.dump(config, f, indent=4)
        except:
            pass
            
    def T(self, key):
        return TRANSLATIONS.get(self.language, TRANSLATIONS["en"]).get(key, key)
